# Site settings
title: Jade's Lens
description: Interesting things I come across
baseurl: "/photos"
url: "https://jadeattard.github.io"
author:

# Collection settings
collections:
  photos:

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown
